### ISSUE TITLE
Inproper use of eleventy-photo-gallery without attribution

### ISSUE THREAD

**Issue by tannerdolby** [ronakjethwa/ronakjethwa.photos#21]
Hey there @ronakjethwa !

If you want to use eleventy-photo-gallery template, you will need to generate a new project from the template via this link on the repo: https://github.com/tannerdolby/eleventy-photo-gallery/generate

Otherwise you're straight up copying the project and putting your name on it. Could you please use the proper attribution?

**Comment by tannerdolby** [comment]
I needed to remind myself how the [MIT License](https://en.wikipedia.org/wiki/MIT_License) worked. You have the freedom to use/modify the project as its open-source. I see you have kept the original [LICENSE](https://github.com/ronakjethwa/ronakjethwa.photos/blob/main/LICENSE) with my attribution so I'm going to go ahead and close this issue. Sorry for the trouble!

**Comment by rjethwa1-godaddy** [comment]
Hey, thanks @tannerdolby for reaching out with the concerns. Let me know if you have decide to change how the license works, and I can change how things are and create a new version out of it.

Thanks for the sweet repository, btw!

**Comment by tannerdolby** [comment]
@rjethwa1-godaddy No problem! Thanks for getting back to me. I'm happy to hear you are finding the repository valuable :) Feel free to submit any [feature requests](https://github.com/tannerdolby/eleventy-photo-gallery/issues) if there is other functionality you would like to see in the template.

You don't necessarily have to change your repo here, but I intended the project to be a "template" so users could generate their own photo gallery projects from my base template via the "Use this template" button: https://github.com/tannerdolby/eleventy-photo-gallery/generate

<img width="428" alt="Screen Shot 2023-06-22 at 7 34 37 PM" src="https://github.com/ronakjethwa/ronakjethwa.photos/assets/48612525/8d1a5ce6-09cf-4bee-b9e5-c9f09da09325">

---------

Here is one example of someone who is using the photo gallery template in the intended way:
- https://github.com/GitOffMyCode/eleventy-photo-gallery

<img width="328" alt="Screen Shot 2023-06-22 at 7 29 53 PM" src="https://github.com/ronakjethwa/ronakjethwa.photos/assets/48612525/4065d701-e0d1-408a-9d03-1c8a75b3ebf3">
